##===
##a,b,c

python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikipedia5x_60p/workdir_7b --experiment_name eval7b_wikipedia5x_60p --output_folder ../output/output_wikipedia5x_60p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikipedia5x_70p/workdir_7b --experiment_name eval7b_wikipedia5x_70p --output_folder ../output/output_wikipedia5x_70p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikipedia5x_80p/workdir_7b --experiment_name eval7b_wikipedia5x_80p --output_folder ../output/output_wikipedia5x_80p  --run_every 2

##====
##d,e,f

python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikipedia50x_60p/workdir_7b/ --experiment_name eval7b_wikipedia50x_60p --output_folder ../output/output_wikipedia50x_60p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikipedia50x_70p/workdir_7b/ --experiment_name eval7b_wikipedia50x_70p --output_folder ../output/output_wikipedia50x_70p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikipedia50x_80p/workdir_7b/ --experiment_name eval7b_wikipedia50x_80p --output_folder ../output/output_wikipedia50x_80p  --run_every 2

##====
##g,h,i

python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_stackexchange50x_60p/workdir_7b/ --experiment_name eval7b_stackexchange50x_60p --output_folder ../output/output_stackexchange50x_60p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_stackexchange50x_70p/workdir_7b/ --experiment_name eval7b_stackexchange50x_70p --output_folder ../output/output_stackexchange50x_70p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_stackexchange50x_80p/workdir_7b/ --experiment_name eval7b_stackexchange50x_80p --output_folder ../output/output_stackexchange50x_80p  --run_every 2

##====
##j,k,l

python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikistack50x_80p/workdir_7b/ --experiment_name eval7b_wikistack50x_80p --output_folder ../output/output_wikistack50x_80p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikistack50x_80p_b/workdir_7b/ --experiment_name eval7b_wikistack50x_80p_b --output_folder ../output/output_wikistack50x_80p_b  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_stackwiki50x_80p/workdir_7b/ --experiment_name eval7b_stackwiki50x_80p --output_folder ../output/output_stackwiki50x_80p  --run_every 2

##====
##m,n,o

python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_arxiv50x_60p/workdir_7b/ --experiment_name eval7b_arxiv50x_60p --output_folder ../output/output_arxiv50x_60p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_arxiv50x_70p/workdir_7b/ --experiment_name eval7b_arxiv50x_70p --output_folder ../output/output_arxiv50x_70p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_arxiv50x_80p/workdir_7b/ --experiment_name eval7b_arxiv50x_80p --output_folder ../output/output_arxiv50x_80p  --run_every 2

##====
##p,q,r

python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikipedia50x_90p/workdir_7b/ --experiment_name eval7b_wikipedia50x_90p --output_folder ../output/output_wikipedia50x_90p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_stackexchange50x_90p/workdir_7b/ --experiment_name eval7b_stackexchange50x_90p --output_folder ../output/output_stackexchange50x_90p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikipedia25x_80p/workdir_7b/ --experiment_name eval7b_wikipedia25x_80p --output_folder ../output/output_wikipedia25x_80p  --run_every 2

##====
##s,t

python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikipedia5x_90p/workdir_7b/ --experiment_name eval7b_wikipedia5x_90p --output_folder ../output/output_wikipedia5x_90p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikipedia25x_90p/workdir_7b --experiment_name eval7b_stackexchange25x_90p --output_folder ../output/output_stackexchange25x_90p  --run_every 2

##====
##u

python evaluate.py    --experiment_ckpt /lustre/home/bowen.tan/workspace/Jul28/mbzuai_llm/workdir_7b --experiment_name eval7b_vanilla --output_folder ../output/output_vanilla  --run_every 2

##====
##v

python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_stackexchange25x_90p/workdir_7b --experiment_name eval7b_stackexchange25x_90p --output_folder ../output/output_stackexchange25x_90p  --run_every 2

##====
##w,x,y,z

python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_stackexchange5x_90p/workdir_7b --experiment_name eval7b_stackexchange5x_90p --output_folder ../output/output_stackexchange5x_90p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_stackexchange25x_80p/workdir_7b/ --experiment_name eval7b_stackexchange25x_80p --output_folder ../output/output_stackexchange25x_80p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikidefault25x_80p/workdir_7b/ --experiment_name eval7b_wikidefault25x_80p --output_folder ../output/output_wikidefault25x_80p  --run_every 2
python evaluate.py    --experiment_ckpt /lustre/scratch/users/william.neiswanger/mbzuai_llm_wikipedia25xcontd_80p/workdir_7b --experiment_name eval7b_wikipedia25xcontd_80p --output_folder ../output/output_wikipedia25xcontd_80p  --run_every 2
